# Server Configuration
server.port=8081

# Application Name
spring.application.name=authem-auth-service

# Database Connection (MySQL)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/authem_user_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Codex@1309}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Automatically escape ALL column & table names (solves reserved keyword errors like 'condition')
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

# Custom Authem JWT Settings
authem.jwt.secret=${JWT_SECRET:ggvrp6JIXRYW53CdyBFJ4nLzjI5OwGHSPSfESB8HRhg=}
authem.jwt.expiration-ms=86400000